// Generated by KofuScript 0.0.3-alpha.2
var present = console.log;
// Generated by KofuScript 0.0.3-alpha.2
var app, name, num;
app = document.getElementById('app');
num = 88;
present(num);
name = {
	value: 'arthur',
	update: function(newName) {
		this.value = newName;
		return this.render();
	},
	render: function() {
		return (app.innerHTML =
			'<h1 onclick="promptForName()">You whack from ' + this.value + '</h1>');
	}
};
window.promptForName = function(e) {
	var newName;
	newName = window.prompt('Lets Change Your Name');
	return name.update(newName);
};
name.render();
